### ISSUE TITLE
cohttp doesn't not compile with uri 2.0.0

### ISSUE THREAD

**Issue by hongchangwu** [mirage/ocaml-cohttp#640]
Got:

```
File "cohttp/src/link.ml", line 22, characters 19-24:
Error: Unbound value Uri.t_of_sexp
```

**Comment by mseri** [comment]
The opam files have been updated in opam repository but not on master. Can you please send a PR updating the bounds? There is already a WIP PR to move to the new Uri, but that would fix the issue in the meanwhile

**Comment by mseri** [comment]
We should be able to merge https://github.com/mirage/ocaml-cohttp/pull/634 and close this issue soon

**Comment by mseri** [comment]
Master works now, and https://github.com/ocaml/opam-repository/pull/12833 will make it available upstream
